import {Class, Semester, Year} from "../interfaces/interfaces";
import {ClassType} from "../const";

const FIRST_SEMESTER_CLASSES: Class[] = [
  {
    "count": 1,
    "name": "Data Structures",
    "nameRo": "Structuri de Date",
    "short": "SD",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1ZLLULuIvSjbyc80wEGDLGCezWjlhelqG?usp=sharing",
    "photo": "https://mir-s3-cdn-cf.behance.net/project_modules/1400_opt_1/b5277873948669.5c1ed6583b53f.jpg",
    "site": "https://profs.info.uaic.ro/~sd",
    "password": "sd SD202021",
    "type": ClassType.NORMAL,
  },
  {
    "count": 2,
    "name": "Computer Architecture and Operating Systems",
    "nameRo": "Arhitectura Calculatoarelor și Sisteme de Operare",
    "short": "ACSO",
    "credits": 5,
    "photo": "https://i.postimg.cc/yYf7dvCQ/1435061-609.jpg",
    "materials": "https://drive.google.com/drive/folders/1CMRZlLSRfb1xZmEyY3pHlHjmDloG51eo?usp=sharing",
    "site": "https://profs.info.uaic.ro/~rvlad/stud.html",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 3,
    "name": "Logics for Computer Science",
    "nameRo": "Logică pentru Informatică",
    "short": "Logică",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1oJ3ZUi6U8vO8u8CtVEDeAiPxH01ft2JV?usp=sharing",
    "photo": "https://i.postimg.cc/G3yM920Z/birmingham-museums-trust-e0w-BK0x-JXYQ-unsplash.jpg",
    "site": "https://profs.info.uaic.ro/~logica",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 4,
    "name": "Mathematics",
    "nameRo": "",
    "short": "Math",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1Wd7hRxnQvgHZd2-MZmX7_pdsfB-DjSpf?usp=sharing",
    "photo": "https://i.postimg.cc/TYSwcgR3/istockphoto-536754333-612x612.jpg",
    "site": "https://profs.info.uaic.ro/~andreea.arusoaie/mate.html",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 5,
    "name": "Introduction to Programming",
    "nameRo": "",
    "short": "IP",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/16--eviquuiV7dSIhYxKdu096SSpzBrG9?usp=sharing",
    "photo": "https://i.postimg.cc/pdQLxSKm/1-I5-Pe-It-Qbk-FDw-YGz4x-Mzw-Mg.jpg",
    "site": "https://profs.info.uaic.ro/~introp",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 6,
    "name": "English Language I",
    "nameRo": "",
    "short": "English",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1_rIjqlUQefGNzR-KXYu0f0rik_YHNtTb?usp=sharing",
    "photo": "https://i.postimg.cc/90kWJHHn/The-Bennu-Bird-Ancient-Egyptian-Symbols-Egypt-Tours-Portal.jpg",
    "site": "https://profs.info.uaic.ro/~augusto.perez",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 7,
    "name": "Competitive Programming",
    "nameRo": "",
    "short": "PC",
    "credits": 3,
    "materials": "",
    "photo": "https://i.postimg.cc/MGYqgQ8R/left-right-brain-science-colors-art-mentality-vector-illustration-flat-style-204797622.jpg",
    "site": "https://students.info.uaic.ro/~alexandru.ionita/pc/index.html",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 8,
    "name": "",
    "nameRo": "Pedagogie",
    "short": "PE",
    "credits": 1,
    "materials": "https://drive.google.com/drive/folders/1rPZsDCcoPzi1aYBpvq1HgfBu-LYxLrLK?usp=sharing",
    "photo": "https://i.postimg.cc/LXCR8F58/the-art-teacher-ingrid-hyde.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 9,
    "name": "Physical Education",
    "nameRo": "",
    "short": "PE",
    "credits": 1,
    "materials": "",
    "photo": "https://i.postimg.cc/C5R0ZrnH/2014-muhammad-ali-sonny-liston-demaryius-thomas-richesson-sports-art-1200x900.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
];

const SECOND_SEMESTER_CLASSES: Class[] = [
  {
    "count": 1,
    "name": "Object Oriented Programming",
    "nameRo": "",
    "short": "OOP",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/18PGvvs_iXxleo34OisrIyOz6xDMoKENO?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/view/fii-poo",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 2,
    "name": "Operating Systems",
    "nameRo": "",
    "short": "SO",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1V6bgZXlf8pgVSt8qGdjuD65MYneqrbcy?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~vidrascu/SO",
    "password": "so2020 1+2=3",
    "type": ClassType.NORMAL,
  },
  {
    "count": 3,
    "name": "Algebraic Foundations of Computer Science",
    "nameRo": "",
    "short": "FAI",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1kNCBPjuDhf1xqkyYr8U786xSDRpnlmRR?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~fltiplea/AFCS/AFCS.html",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 4,
    "name": "Probabilities and Statistics",
    "nameRo": "",
    "short": "PS",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1qBU8OfQcdEyxAQJx1oLZKVE-HtiSWEWL?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~adrian.zalinescu/PS.html",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 5,
    "name": "Algorithms Design",
    "nameRo": "",
    "short": "PA",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1eCysOHOyXOlNwjPsOrnTH-1UHftD3ZMK?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/site/fiicoursepa",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 6,
    "name": "English Language II",
    "nameRo": "",
    "short": "English",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/15bJzxNOgMBbCAj8dMdTgknG9wKPiKtw5?usp=sharing",
    "photo": "https://i.postimg.cc/90kWJHHn/The-Bennu-Bird-Ancient-Egyptian-Symbols-Egypt-Tours-Portal.jpg",
    "site": "https://profs.info.uaic.ro/~augusto.perez",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 7,
    "name": "Competitive Programming",
    "nameRo": "",
    "short": "PC",
    "credits": 3,
    "materials": "",
    "photo": "",
    "site": "https://students.info.uaic.ro/~alexandru.ionita/pc/index.html",
    "password": "",
    "type": ClassType.FACULTY,
  },

  /* TODO */
  {
    "count": 8,
    "name": "Ethics and Academic Integrity",
    "nameRo": "",
    "short": "EIA",
    "credits": 1,
    "materials": "https://drive.google.com/drive/folders/1xILmYT21HPUWfQM4PRIdf6nezPCG8LlO?usp=sharing",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 9,
    "name": "Physical Education II",
    "nameRo": "",
    "short": "Sport",
    "credits": 1,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
];

const FIRST_SEMESTER: Semester = {
  semester: 1,
  semesterCount: 1,
  classes: FIRST_SEMESTER_CLASSES,
};

const SECOND_SEMESTER: Semester = {
  semester: 1,
  semesterCount: 2,
  classes: SECOND_SEMESTER_CLASSES,
};


export const B_FIRST_YEAR: Year = {
  name: 'First Year',
  count: 1,
  semesters: [
    FIRST_SEMESTER,
    SECOND_SEMESTER,
  ],
};
