import {Class, Semester, Year} from "../interfaces/interfaces";
import {ClassType} from "../const";

const FIRST_SEMESTER_CLASSES: Class[] = [
  {
    "count": 1,
    "name": "Data Structures",
    "nameRo": "Structuri de Date",
    "short": "SD",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1guVM4bTpmDSXxTiLgh2cJEOMwWj4xGY8?usp=sharing",
    "photo": "https://mir-s3-cdn-cf.behance.net/project_modules/1400_opt_1/b5277873948669.5c1ed6583b53f.jpg",
    "site": "https://profs.info.uaic.ro/~sd",
    "password": "sd SD20232024",
    "type": ClassType.NORMAL,
  },
  {
    "count": 2,
    "name": "Computer Architecture and Operating Systems",
    "nameRo": "Arhitectura Calculatoarelor si Sisteme de Operare",
    "short": "ACSO",
    "credits": 5,
    "photo": "https://i.postimg.cc/yYf7dvCQ/1435061-609.jpg",
    "materials": "https://drive.google.com/drive/folders/1HaqhrzA6llCJNUq7HqdZuxn-0C_n3pSK?usp=sharing",
    "site": "https://profs.info.uaic.ro/~rvlad/stud.html",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 3,
    "name": "Logics for Computer Science",
    "nameRo": "Logica pentru Informatica",
    "short": "Logica",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1bsHSUEwCrNd2y_U_XR5ZoquuNvH6cJ6D?usp=sharing",
    "photo": "https://i.postimg.cc/G3yM920Z/birmingham-museums-trust-e0w-BK0x-JXYQ-unsplash.jpg",
    "site": "https://logicincs.github.io/",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 4,
    "name": "Math",
    "nameRo": "Matematica",
    "short": "Mate",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1cfmZ9LbVWKJr1Y_uaefacwBGUn7UNcXz?usp=sharing",
    "photo": "https://i.postimg.cc/TYSwcgR3/istockphoto-536754333-612x612.jpg",
    "site": "https://sites.google.com/view/matematica2023-2024",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 5,
    "name": "Introduction to Programming",
    "nameRo": "Introducere in Programare",
    "short": "IP",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1BezuUIvHkztnMTjDcCJ0gYJ2vKOF241Z?usp=sharing",
    "photo": "https://i.postimg.cc/pdQLxSKm/1-I5-Pe-It-Qbk-FDw-YGz4x-Mzw-Mg.jpg",
    "site": "https://profs.info.uaic.ro/~introp",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 6,
    "name": "English Language I",
    "nameRo": "Engleza",
    "short": "Engleza",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1pyIovesgDAxD822SmpjZoYIjsKj5H-LH?usp=sharing",
    "photo": "https://i.postimg.cc/90kWJHHn/The-Bennu-Bird-Ancient-Egyptian-Symbols-Egypt-Tours-Portal.jpg",
    "site": "https://profs.info.uaic.ro/~augusto.perez",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 7,
    "name": "Competitive Programming",
    "nameRo": "Programare Competitiva",
    "short": "PC",
    "credits": 3,
    "materials": "",
    "photo": "https://i.postimg.cc/MGYqgQ8R/left-right-brain-science-colors-art-mentality-vector-illustration-flat-style-204797622.jpg",
    "site": "https://students.info.uaic.ro/~alexandru.ionita/pc/index.html",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 8,
    "name": "Pedagogy",
    "nameRo": "Pedagogie",
    "short": "Pedagogie",
    "credits": 1,
    "materials": "https://drive.google.com/drive/folders/16B6XCJRPkPkybv1d1TG-wOh-YRaUPewV?usp=sharing",
    "photo": "https://i.postimg.cc/LXCR8F58/the-art-teacher-ingrid-hyde.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 9,
    "name": "Physical Education",
    "nameRo": "Educatie Fizica",
    "short": "Sport",
    "credits": 1,
    "materials": "",
    "photo": "https://i.postimg.cc/C5R0ZrnH/2014-muhammad-ali-sonny-liston-demaryius-thomas-richesson-sports-art-1200x900.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
];

const SECOND_SEMESTER_CLASSES: Class[] = [
  {
    "count": 1,
    "name": "Object Oriented Programming",
    "nameRo": "Programare Orientata Obiect",
    "short": "OOP",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1zCleJlXHf2BKm10qqkE3eGqW75_3-AAW?usp=sharing",
    "photo": "https://i.postimg.cc/tgnRbHst/d730df0856fda05714d3a17dd85590e8.jpg",
    "site": "https://sites.google.com/view/fii-poo",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 2,
    "name": "Operating Systems",
    "nameRo": "Sisteme de Operare",
    "short": "SO",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/15OTn0CI7imWqXjt0NkXNuafKwMRhNEGW?usp=sharing",
    "photo": "https://i.postimg.cc/Pf2gSRxt/linux.png",
    "site": "https://profs.info.uaic.ro/~vidrascu/SO",
    "password": "so2020 1+2=3",
    "type": ClassType.NORMAL,
  },
  {
    "count": 3,
    "name": "Algebraic Foundations of Computer Science",
    "nameRo": "Fundamente Algebrice ale Informaticii",
    "short": "FAI",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1I36Y-f_om-Ox9BkyIyI5J5wnKw-_6d1K?usp=sharing",
    "photo": "https://i.postimg.cc/SKF3X0ZG/fai.jpg",
    "site": "https://profs.info.uaic.ro/~fltiplea/AFCS/AFCS.html",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 4,
    "name": "Probabilities and Statistics",
    "nameRo": "Probabilitati si Statistica",
    "short": "PS",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1wQHIvIMmtShvfJyjQMedu4XUHHs3Gedw?usp=sharing",
    "photo": "https://i.postimg.cc/85w0n7Ty/statistic.png",
    "site": "https://profs.info.uaic.ro/~adrian.zalinescu/PS.html",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 5,
    "name": "Algorithms Design",
    "nameRo": "Proiectarea Algoritmilor",
    "short": "PA",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1--ilhjnmy9DD4ugCUQphiM6wYsr5f7Ds?usp=sharing",
    "photo": "https://i.postimg.cc/FRPTVwx8/45603390a097ffa44aea9204544b05b0.png",
    "site": "https://sites.google.com/site/fiicoursepa",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 6,
    "name": "English Language II",
    "nameRo": "Engleza",
    "short": "Engleza",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/170zZbaRAVgXEqszR5YQhN5hu_AZv4FVt?usp=sharing",
    "photo": "https://i.postimg.cc/90kWJHHn/The-Bennu-Bird-Ancient-Egyptian-Symbols-Egypt-Tours-Portal.jpg",
    "site": "https://profs.info.uaic.ro/~augusto.perez",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 7,
    "name": "Competitive Programming",
    "nameRo": "Programare Competitiva",
    "short": "PC",
    "credits": 3,
    "materials": "",
    "photo": "https://i.postimg.cc/MGYqgQ8R/left-right-brain-science-colors-art-mentality-vector-illustration-flat-style-204797622.jpg",
    "site": "https://students.info.uaic.ro/~alexandru.ionita/pc/index.html",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 8,
    "name": "Pedagogy",
    "nameRo": "Pedagogie",
    "short": "Pedagogie",
    "credits": 1,
    "materials": "",
    "photo": "https://i.postimg.cc/LXCR8F58/the-art-teacher-ingrid-hyde.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 9,
    "name": "Ethics and Academic Integrity",
    "nameRo": "Etica si Integritate Academica",
    "short": "EIA",
    "credits": 1,
    "materials": "https://drive.google.com/drive/folders/1YlmOMSt7Xae2cIgUr2sFMNArth6AxCHo?usp=sharing",
    "photo": "https://i.postimg.cc/3xVt4qT9/Ethics-and-the-Common-Good-Abstract-vs-Experiential-1.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 10,
    "name": "Physical Education II",
    "nameRo": "Educatie Fizica",
    "short": "Sport",
    "credits": 1,
    "materials": "",
    "photo": "https://i.postimg.cc/C5R0ZrnH/2014-muhammad-ali-sonny-liston-demaryius-thomas-richesson-sports-art-1200x900.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
];

const FIRST_SEMESTER: Semester = {
  semester: 1,
  semesterCount: 1,
  classes: FIRST_SEMESTER_CLASSES,
};

const SECOND_SEMESTER: Semester = {
  semester: 1,
  semesterCount: 2,
  classes: SECOND_SEMESTER_CLASSES,
};


export const B_FIRST_YEAR: Year = {
  name: 'First Year',
  count: 1,
  semesters: [
    FIRST_SEMESTER,
    SECOND_SEMESTER,
  ],
};
