import {Class, Semester, Year} from "../interfaces/interfaces";
import {ClassType} from "../const";

export const FIRST_SEMESTER_CLASSES: Class[] = [
  {
    "count": 1,
    "name": "Machine Learning",
    "nameRo": "",
    "short": "ML",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/14_M-ZG4I7O-tFbAVlBfvxa6x3UeRsBI-?usp=sharing",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 2,
    "name": "Information Security",
    "nameRo": "",
    "short": "SI",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1fX5sgvvDIAfC6ji7BCLLEyjZUYP7O7l-?usp=sharing",
    "photo": "",
    "site": "https://www.flt-info.eu/course/isec/",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 3,
    "name": "Artificial Intelligence",
    "nameRo": "",
    "short": "AI",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1E-bs4MSnoedECHpnsvcjIwTJ3dPSUeWd?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/view/iafii/home",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 4,
    "name": "Python Programming",
    "nameRo": "",
    "short": "Python",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1RFR_pQvLtsCPIOkQmZ6IO9k6qyTavKQE?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/site/fiipythonprogramming/",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 5,
    "name": "Introduction to .NET",
    "nameRo": "",
    "short": ".NET",
    "credits": 4,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 6,
    "name": "Physical Systems Development Using Microprocessors",
    "nameRo": "",
    "short": "DSFUM",
    "credits": 4,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 7,
    "name": "Neural Networks",
    "nameRo": "",
    "short": "NN",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1KQX0f_1RGB1GNq7egNleV0ipsH81z06Z?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/view/rbenchea/neural-networks",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 8,
    "name": "3D Computer Animation",
    "nameRo": "",
    "short": "Animations",
    "credits": 4,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 9,
    "name": "Probabilistic Programming and Modeling",
    "nameRo": "",
    "short": "PMP",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 10,
    "name": "Introduction to Mixed Realities",
    "nameRo": "",
    "short": "IRM",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 11,
    "name": "Special Chapters in Operating Systems",
    "nameRo": "",
    "short": "CSSO",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 12,
    "name": "Multiprocessor Programming Techniques",
    "nameRo": "",
    "short": "TPM",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1_Pi2x-gEbrUSSgQo6BKCAtmxpJHHl8fy?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~eonica/mpt/index.html",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 13,
    "name": "Competitive Programming",
    "nameRo": "",
    "short": "PC",
    "credits": 3,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 14,
    "name": "Industry Training II",
    "nameRo": "",
    "short": "Practice",
    "credits": 3,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
];

const SECOND_SEMESTER_CLASSES: Class[] = [
  {
    "count": 1,
    "name": "Numeric Calculus",
    "nameRo": "",
    "short": "CN",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1T1WXuUIYtqaTZuIGnaIGC5YPwKgPprP2?usp=sharing",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 2,
    "name": "Computer Graphics",
    "nameRo": "",
    "short": "GC",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1NspZV-yDLMLAnGQ5LmPx0sHZ3pDFmzqf?usp=sharing",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 3,
    "name": "Diploma Project Development ",
    "nameRo": "",
    "short": "Thesis",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 4,
    "name": "Rule Based Programming",
    "nameRo": "",
    "short": "PBR",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 5,
    "name": "Mobile Development",
    "nameRo": "",
    "short": "Mobile",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1_G-RS3wDjKesjQWc4s3LTDkO47YezJzP?usp=sharing",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 6,
    "name": "Computational Aspects on the Number Theory",
    "nameRo": "",
    "short": "ACTN",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 7,
    "name": "Game Design",
    "nameRo": "",
    "short": "Game Design",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 8,
    "name": "Psychology of the Professional Communication in IT Industry",
    "nameRo": "",
    "short": "PCPIT",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 9,
    "name": "Cloud Computing",
    "nameRo": "",
    "short": "CC",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1UFLab_6cTaVxfjzjJLisJUwLwwV3-WQ8?usp=sharing",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 10,
    "name": "Human-Computer Interaction ",
    "nameRo": "",
    "short": "HCI",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 11,
    "name": "Social Media Networks Analysis",
    "nameRo": "",
    "short": "ARMS",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 12,
    "name": "Petri Nets and Applications",
    "nameRo": "",
    "short": "LFAC 2",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 13,
    "name": "Smart Cards and Their Applications",
    "nameRo": "",
    "short": "SCA",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 14,
    "name": "Automotive specific software engineering",
    "nameRo": "",
    "short": "ISSA",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1fw1Iy9fwiG1q9EuS15qellHcothCwO9Y?usp=sharing",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 15,
    "name": "Modeling of Digital Systems ",
    "nameRo": "",
    "short": "MSD",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 16,
    "name": "Competitive Programming",
    "nameRo": "",
    "short": "PC",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  }
];

const FIRST_SEMESTER: Semester = {
  semester: 1,
  semesterCount: 5,
  classes: FIRST_SEMESTER_CLASSES,
};

const SECOND_SEMESTER: Semester = {
  semester: 2,
  semesterCount: 6,
  classes: SECOND_SEMESTER_CLASSES,
};

export const B_THIRD_YEAR: Year = {
  name: 'Third Year',
  count: 3,
  semesters: [
    FIRST_SEMESTER,
    SECOND_SEMESTER,
  ]
};
