import {Class, Semester, Year} from "../interfaces/interfaces";
import {ClassType} from "../const";

export const FIRST_SEMESTER_CLASSES: Class[] = [
  {
    "count": 1,
    "name": "Machine Learning",
    "nameRo": "Invatare Automata",
    "short": "ML",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/10m5VL7QbCImCdCw1ozvxhbyX9ggKJwZq?usp=sharing",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 2,
    "name": "Information Security",
    "nameRo": "Securitatea Informatiei",
    "short": "SI",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/19jpMmBa8a6jyYupBueWBAK-zatJPAZd1?usp=sharing",
    "photo": "",
    "site": "https://www.flt-info.eu/course/isec/",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 3,
    "name": "Artificial Intelligence",
    "nameRo": "Inteligenta Artificiala",
    "short": "AI",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1kNEMvePTU52dxNO4ZvP5YvnS3lehDmTN?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/view/iafii/home",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 4,
    "name": "Python Programming",
    "nameRo": "Programare in Python",
    "short": "Python",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1sAm-UyN-2MUWpBqbqurAwTOcwZ0t63r_?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/site/fiipythonprogramming/",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 5,
    "name": "Introduction to .NET",
    "nameRo": "Introducere in .NET",
    "short": ".NET",
    "credits": 4,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 6,
    "name": "Physical Systems Development Using Microprocessors",
    "nameRo": "Dezvoltarea Sistemelor Fizice Utilizand Microprocesoare",
    "short": "DSFUM",
    "credits": 4,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 7,
    "name": "Neural Networks",
    "nameRo": "Retele Neuronale",
    "short": "RN",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1GFmVwSwdqABehnNF1AmC0wsG_-17IEXj?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/view/rbenchea/neural-networks",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 8,
    "name": "3D Computer Animation",
    "nameRo": "Animatii 3D",
    "short": "Animatii 3D",
    "credits": 4,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 9,
    "name": "Probabilistic Programming and Modeling",
    "nameRo": "Programare si Modelare Probabilista",
    "short": "PMP",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 10,
    "name": "Introduction to Mixed Realities",
    "nameRo": "Introducerea in Realitatea Mixta",
    "short": "IMR",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 11,
    "name": "Special Chapters in Operating Systems",
    "nameRo": "Capitole Speciale de Sisteme de Operare",
    "short": "CSSO",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 12,
    "name": "Multiprocessor Programming Techniques",
    "nameRo": "Programare Multiprocesor",
    "short": "TPM",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/1Sk6YoVLFLnO7RwZtX9Iy1ZzQ18aq8jq4?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~eonica/mpt/index.html",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 13,
    "name": "Competitive Programming",
    "nameRo": "Programare Competitiva",
    "short": "PC",
    "credits": 3,
    "materials": "",
    "photo": "https://i.postimg.cc/MGYqgQ8R/left-right-brain-science-colors-art-mentality-vector-illustration-flat-style-204797622.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
  {
    "count": 14,
    "name": "Industry Training II",
    "nameRo": "Practica in Industrie",
    "short": "Practica",
    "credits": 3,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  },
];

const SECOND_SEMESTER_CLASSES: Class[] = [
  {
    "count": 1,
    "name": "Numeric Calculus",
    "nameRo": "Calcul Numeric",
    "short": "CN",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1BYvIAZpIi6KlGbvswFa6eL3k9CaUMvgB?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~ancai/CN/",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 2,
    "name": "Computer Graphics",
    "nameRo": "Grafica pe Calculator",
    "short": "Grafica",
    "credits": 4,
    "materials": "https://drive.google.com/drive/folders/1mkz_mC5DYI5yLjWqw9K3kf546lo5l5L7?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~ghirvu/gpc/",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 3,
    "name": "Diploma Project Development ",
    "nameRo": "Elaborare Lucrare de Licenta",
    "short": "Licenta",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.NORMAL,
  },
  {
    "count": 4,
    "name": "Rule Based Programming",
    "nameRo": "Programare Bazata pe Reguli",
    "short": "PBR",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 5,
    "name": "Mobile Development",
    "nameRo": "Tehnici de Programare pe Platforme Mobile",
    "short": "Flutter",
    "credits": 5,
    "materials": "https://drive.google.com/drive/folders/16qu3Zf9bwdpYHcXPdC9BUUZ0r-AvPGdl?usp=sharing",
    "photo": "",
    "site": "https://sites.google.com/view/fiiflutterdev",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 6,
    "name": "Computational Aspects on the Number Theory",
    "nameRo": "Aspecte Computationale in Teoria Numerelor",
    "short": "ACTN",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 7,
    "name": "Game Design",
    "nameRo": "Proiectarea Jocurilor",
    "short": "Game Design",
    "credits": 5,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_1,
  },
  {
    "count": 8,
    "name": "Psychology of the Professional Communication in IT Industry",
    "nameRo": "Psihologia Comunicarii Profesionale in Domeniul IT",
    "short": "PCPIT",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 9,
    "name": "Cloud Computing",
    "nameRo": "Cloud Computing",
    "short": "Cloud",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1Pj3PuXaA75SZPv0j-3_Ltm_bPu6wepvu?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~adria/teach/courses/CloudComputing/",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 10,
    "name": "Human-Computer Interaction",
    "nameRo": "Human-Computer Interaction",
    "short": "HCI",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~busaco/teach/courses/hci/",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 11,
    "name": "Social Media Networks Analysis",
    "nameRo": "Analiza Retelelor Media Sociale",
    "short": "ARMS",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_2,
  },
  {
    "count": 12,
    "name": "Petri Nets and Applications",
    "nameRo": "Retele Petri si Aplicatii",
    "short": "Retele Petri",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 13,
    "name": "Smart Cards and Their Applications",
    "nameRo": "Smart Card-uri si Aplicatii",
    "short": "Smart Card-uri",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 14,
    "name": "Automotive specific software engineering",
    "nameRo": "Ingineria Software Specifica Automobilelor",
    "short": "ISSA",
    "credits": 6,
    "materials": "https://drive.google.com/drive/folders/1Vjqkq12cC-DxGqYQ-nva9_YVNisiAy1z?usp=sharing",
    "photo": "",
    "site": "https://profs.info.uaic.ro/~conti/",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 15,
    "name": "Modeling of Digital Systems",
    "nameRo": "Modelarea Sistemelor Digitale",
    "short": "MSD",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 16,
    "name": "Special Topics on .NET programming",
    "nameRo": "Topici Speciale de Programare .NET",
    "short": ".NET",
    "credits": 6,
    "materials": "",
    "photo": "",
    "site": "",
    "password": "",
    "type": ClassType.OPTIONAL_3,
  },
  {
    "count": 17,
    "name": "Competitive Programming",
    "nameRo": "Programare Competitiva",
    "short": "PC",
    "credits": 6,
    "materials": "",
    "photo": "https://i.postimg.cc/MGYqgQ8R/left-right-brain-science-colors-art-mentality-vector-illustration-flat-style-204797622.jpg",
    "site": "",
    "password": "",
    "type": ClassType.FACULTY,
  }
];

const FIRST_SEMESTER: Semester = {
  semester: 1,
  semesterCount: 5,
  classes: FIRST_SEMESTER_CLASSES,
};

const SECOND_SEMESTER: Semester = {
  semester: 2,
  semesterCount: 6,
  classes: SECOND_SEMESTER_CLASSES,
};

export const B_THIRD_YEAR: Year = {
  name: 'Third Year',
  count: 3,
  semesters: [
    FIRST_SEMESTER,
    SECOND_SEMESTER,
  ]
};
