export const GET_CLASSES = 1;
export const GET_LINKS = 2;
export const GET_USER_DATA = 3;
export const SET_AUTH_STATUS = 4;
export const GET_USER_ADVANCED_DATA = 5;
export const SET_MATERIALS_LOADING = 6;
export const SET_LINKS_LOADING = 7;
export const SET_USER_DATA_LOADING = 8;
export const GET_RESOURCES = 9;
export const SET_RESOURCE_LOADING = 10;

const ACTIONS = [
    GET_CLASSES,
    GET_LINKS,
    GET_USER_DATA,
    GET_USER_ADVANCED_DATA,
    SET_AUTH_STATUS,
    SET_MATERIALS_LOADING,
    SET_LINKS_LOADING,
    SET_USER_DATA_LOADING,
    GET_RESOURCES,
    SET_RESOURCE_LOADING,
]

export default ACTIONS;
